name: release-workflow
run-name: ${{ github.actor }} создал релиз ${{ github.ref_name }}
on:
  push:
    tags:
      - 'rc-*.*.*'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.16.0'
      - run: npm install
      - run: npm run test
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.16.0'
      - run: npm install
      - run: npm run build
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.16.0'
      - run: npm install axios
      - name: Generate release report
        env:
          TRACKER_AUTHORIZATION_KEY: ${{ secrets.TRACKER_AUTHORIZATION_KEY }}
          ACTOR: ${{ github.actor }}
          RELEASE_VERSION: ${{ github.ref_name }}
        run: npm run report-release
  # deploy:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: '16.16.0'
  #     - run: echo reached deploy step
